<?php
function noticeme_entity_view_alter(&$build, $type) {
  if ($type == 'user') {
    $type = 'account';
  }
  if (($entity = @$build['#' . $type]) && ($info = noticeme_object_info($type, $entity))) {
    $build['noticeme'] = array(
      '#theme' => 'noticeme',
      '#info' => $info,
    );
  }
}

function noticeme_theme() {
  $theme_params = array(
    'path' => drupal_get_path('module', 'noticeme') . '/templates',
  );
  return array(
    'noticeme' => array(
      'variables' => array(
        'info' => array(),
      ),
      'template' => 'noticeme',
    )
  );
}

function noticeme_object_info($type, $entity) {
  $uri = entity_uri($type, $entity);
  if (!$uri) {
    return FALSE;
  }
  $info = array();
  $info['url'] = url($uri['path'], array('absolute' => TRUE));
  $info['title'] = entity_label($type, $entity);
  $info['image'] = FALSE;
  $info['description'] = FALSE;
  $info['entity'] = $entity;
  $info['entity_type'] = $type;
  drupal_alter('noticeme_object_info', $info);
  return $info;
}

function noticeme_field_extra_fields() {
  $entity_info = entity_get_info();
  $extra = array();
  foreach ($entity_info as $type => $info) {
    foreach (array_keys($info['bundles']) as $bundle) {
      $extra[$type][$bundle] = array(
        'display' => array(
          'noticeme' => array(
            'label' => t('Noticeme'),
            'description' => t('Social Media Buttons'),
            'weight' => 0,
          ),
        ),
      );
    }
  }
  return $extra;
}

/**
 * Implements hook_init().
 */
function noticeme_init() {
  drupal_add_js(drupal_get_path('module', 'noticeme') . '/noticeme.js');
  drupal_add_js(array('noticeme' => array(
    'fblang' => variable_get('noticeme_fblang', 'en_US'),
  )), 'setting');
}

/**
 * Implements hook_rdf_namespaces().
 */
function noticeme_rdf_namespaces() {
  return array(
    'fb'  => 'http://www.facebook.com/2008/fbml',
  );
}
