<?php
/**
 * @file
 * Adds a field (called social media) for displaying facebook, google+ and
 * twitter buttons and adds open graph as well as http://schema.org metadata
 * to the html header.
 */

module_load_include('inc', 'noticeme', '/noticeme.field');
module_load_include('inc', 'noticeme', '/noticeme.forms');

/**
 * Implements hook_init().
 * Add noticeme.js and write social media data into page head.
 */
function noticeme_init() {
  global $language;
  drupal_add_css(drupal_get_path('module', 'noticeme') . '/noticeme.css');
  drupal_add_js(drupal_get_path('module', 'noticeme') . '/js/noticeme.js');
  drupal_add_js(array('noticeme' => array('languages' => array(
    'facebook' => variable_get('noticeme_' . $language->language . '_facebook', 'en_US'),
    'google' => variable_get('noticeme_' . $language->language . '_google', 'en-US'),
    'twitter' => variable_get('noticeme_' . $language->language . '_twitter', 'en'),
  ))), 'setting');
  $info = noticeme_page_info();
  $headers = array();
  $headers[] = array('property' => 'og:title', 'content' => @$info['title']);
  $headers[] = array('property' => 'og:url', 'content' => @$info['url']);
  $headers[] = array('property' => 'og:image', 'content' => @$info['image']);
  $headers[] = array('property' => 'og:description', 'content' => @$info['description']);
  $headers[] = array('property' => 'og:type', 'content' => @$info['og_type']);
  $headers[] = array('property' => 'og:site_name', 'content' => variable_get('site_name'));

  if (strlen(trim(variable_get('noticeme_fb_admins'))) > 0) {
    $headers[] = array(
      'property' => 'og:admins',
      'content' => variable_get('noticeme_fb_admins'),
    );
  }
  if (strlen(trim(variable_get('noticeme_fb_appid'))) > 0) {
    $headers[] = array(
      'property' => 'og:admins',
      'content' => variable_get('noticeme_fb_appid'),
    );
  }
  $headers[] = array('itemprop' => 'name', 'content' => $info['title']);
  $headers[] = array('itemprop' => 'description', 'content' => $info['description']);
  foreach ($headers as $key => $header) {
    drupal_add_html_head(array(
      '#tag' => 'meta',
      '#attributes' => $header,
    ), 'noticeme_' . $key);
  }
}

/**
 * Implements hook_preprocess_html().
 */
function noticeme_preprocess_html(&$vars) {
  $info = noticeme_page_info();
  if ($type = @$info['schema_type']) {
    $vars['rdf_namespaces'] .= ' itemscope itemtype="http://schema.org/' . $type . '"';
  }
}

/**
 * Implements hook_menu().
 */
function noticeme_menu() {
  return array(
    'admin/config/search/noticeme' => array(
      'title' => 'Noticeme',
      'description' => 'Configure global settings for social media buttons.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('noticeme_admin_settings'),
      'file' => 'noticeme.admin.inc',
      'access arguments' => array('administer site configuration'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function noticeme_theme() {
  return array(
    //theme facebook like button
    'facebook_like' => array(
      'variables' => array(
        'href' => FALSE,
        'layout' => 'box_count',
        'send' => 0,
        'show-faces' => 0,
        'action' => 0,
        'colorscheme' => 'light',
        'font' => 'lucida grande',
      ),
      'file' => 'noticeme.theme.inc',
    ),
    //theme google+ button
    'google_plus' => array(
      'variables' => array(
        'href' => FALSE,
        'size' => 'medium',
        'annotation' => 'info',
      ),
      'file' => 'noticeme.theme.inc',
    ),
    //theme twitter button
    'twitter_tweet' => array(
      'variables' => array(
        'url' => FALSE,
        'text' => '',
        'count' => 'show',
        'via' => '',
        'size' => 'small',
        'related' => '',
        'hashtags' => '',
      ),
      'file' => 'noticeme.theme.inc',
    ),
    //theme the languages table used in the noticeme settings page
    //under admin/config/search/noticeme
    'noticeme_languages' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Build social media information for current page/url.
 *
 * Uses data from noticeme_site_info() as default, overrides it with data extracted
 * from the entity, data stored in noticeme fields and finally
 * hook_noticeme_field_info_alter().
 *
 * @return
 *   An array with global social media information.
 *   See noticeme_get_info_from_entity_noticeme_field() for details.
 */
function noticeme_page_info() {
  $info = &drupal_static(__FUNCTION__);
  if (!isset($info)) {
    $menu_item = menu_get_item();

    //default to global values and override with info extracted from the entity
    $info = array_merge(noticeme_site_info(), noticeme_entity_info($menu_item));
    //let other modules extract info from entity types they define
    drupal_alter('noticeme_entity_info', $info, $menu_item);

    //override with info stored in the entity's noticeme field
    $info = array_merge($info, noticeme_field_info($info, $menu_item));
    //let other modules set info for noticeme fields that are attached to entity types they define
    drupal_alter('noticeme_field_info', $info, $menu_item);
  }
  return $info;
}

/**
 * Collects site-global social media information.
 *
 * This data will be overridden by data stored in entities and data stored in
 * noticeme fields.
 *
 * @return
 *   An array with global social media information.
 *   See noticeme_get_info_from_entity_noticeme_field() for details.
 */
function noticeme_site_info() {
  $info = array();
  $info['url'] = url(request_path(), array('absolute' => TRUE));
  $info['title'] = variable_get('site_name');
  $info['description'] = variable_get('site_slogan');
  if (strlen(theme_get_setting('logo_path')) > 0) {
    $info['image'] = file_create_url(theme_get_setting('logo_path'));
  }
  else {
    $info['image'] = FALSE;
  }

  //let other modules alter global info
  drupal_alter('noticeme_site_info', $info);
  return $info;
}

/**
 * Build social media info from data stored in the entity.
 *
 * Collects info from predefined entities. For custom entity types implement
 * hook_noticeme_entity_info_alter() which is called after this function.
 * @see noticeme_page_info().

 * @param $menu_item
 *   The current page's menu router item.
 *
 * @return
 *   An array with global social media information.
 *   See noticeme_get_info_from_entity_noticeme_field() for details.
 */
function noticeme_entity_info($menu_item) {
  switch($menu_item['page_callback']) {
    case 'node_page_view':
      $page_info = noticeme_get_info_from_predefined_entity_data('node', $menu_item['page_arguments'][0]);
      break;

    case 'comment_permalink':
      $page_info = noticeme_get_info_from_predefined_entity_data('comment', $menu_item['page_arguments'][0]);
      break;

    case 'user_view_page':
      $page_info = noticeme_get_info_from_predefined_entity_data('user', $menu_item['page_arguments'][0]);
      break;

    default:
      $page_info = array();
  }
  return $page_info;
}

/**
 * Build social media info out of predefined entity types.
 *
 * Builds info for the entity types node, comment and user by using data
 * stored in the entity (like node title, image fields,...).
 *
 * @param $entity_type
 *   The entity's type
 *
 * @param $entity
 *   The entity for which we extract social media info.
 *
 * @return array
 *   An associative array containing social media info.
 *   See noticeme_get_info_from_entity_noticeme_field() for details.
 */
function noticeme_get_info_from_predefined_entity_data($entity_type, $entity) {
  $info = array();
  switch ($entity_type) {
    case 'node':
      $info['title'] = $entity->title;
      if ($items = field_get_items('node', $entity, 'field_image')) {
        $info['image'] = file_create_url($items[0]['uri']);
      }
      if ($items = field_get_items('node', $entity, 'body')) {
        if (array_key_exists('safe_summary', $items[0])) {
          if (drupal_strlen(trim($items[0]['safe_summary'])) > 0) {
            $info['description'] = drupal_html_to_text($items[0]['safe_summary']);
          }
          elseif (drupal_strlen(trim($items[0]['safe_value'])) > 0) {
            $info['description'] = drupal_html_to_text($items[0]['safe_value']);
          }
        }
      }
      $info['og_type'] = 'article';
      $info['schema_type'] = 'Article';
      break;

    case 'comment':
      $info['title'] = $entity->subject;
      if ($items = field_get_items('comment', $entity, 'comment_body')) {
        $info['description'] = drupal_html_to_text($items[0]['safe_value']);
      }
      $info['og_type'] = 'article';
      $info['schema_type'] = 'Article';
      break;

    case 'user':
      $info['title'] = $account->name;
      $info['og_type'] = 'website';
      $info['schema_type'] = 'Person';
      break;
  }
  return $info;
}

/*
 * Builds social media info from a noticeme field.
 *
 * Builds info by getting it from a noticeme field which is attached to the entity
 * type we're displaying on the current page.
 *
 * @param $menu_item
 *   The current page's menu router item
 *
 * @return
 *   An array with global social media information.
 *   See noticeme_get_info_from_entity_noticeme_field() for details.
 */
function noticeme_field_info($menu_item) {
  switch($menu_item['page_callback']) {
    case 'node_page_view':
      $info = noticeme_get_info_from_entity_noticeme_field('node',$menu_item['page_arguments'][0]);
      break;

    case 'comment_permalink':
      $info = noticeme_get_info_from_entity_noticeme_field('comment', $menu_item['page_arguments'][0]);
      break;

    case 'user_view_page':
      $info = noticeme_get_info_from_entity_noticeme_field('user', $menu_item['page_arguments'][0]);
      break;

    default:
      $info = array();
  }
  return $info;
}

/**
 * Gets social media info for a given entity's noticeme field.
 *
 * @see noticeme_page_info().
 *
 * @param $entity_type
 *   The given entity's type
 *
 * @param $entity
 *   The entity for which we're looking for social media information
 *
 * @return array
 *   An associative array containing:
 *   - title:       open graph title (og:title)
 *   - og_type:     open graph type (og:type)
 *   - schema_type: schema.org type (itemtype="http:/schema.org/[TYPE]")
 *   - description: open graph description (og:description)
 *   - image:       url to an image representing the current page/url
 */
function noticeme_get_info_from_entity_noticeme_field($entity_type, $entity) {
  if (empty($entity->type)) {
    return array();
  }
  $noticeme_field_ids = _noticeme_field_ids();

  foreach (field_info_instances($entity_type, $entity->type) as $id => $field) {
    //iterate only over noticeme fields
    if (in_array($id, $noticeme_field_ids)) {
      if ($items = field_get_items($entity_type, $entity, $id)) {
        //for all noticeme fields attached to the entity
        foreach ($items as $item) {
          //add all values set in the entity to $info
          foreach ($item as $key => $value) {
            if ($key == 'image' && strlen($value) > 0) {
              $file = file_load($value);
              if ($file) {
                $info['image'] = file_create_url($file->uri);
              }
            }
            elseif (strlen($value) > 0) {
              $info[$key] = $value;
            }
          }
        }
      }
    }
  }
  return $info;
}

/**
 * Get the ids of all noticeme fields
 */
function _noticeme_field_ids() {
  $ids = array();
  $info = field_info_fields();
  foreach ($info as $id => $field) {
    if ($field['type'] == 'noticeme') {
      $ids[] = $id;
    }
  }
  return $ids;
}
